name: Build self=contained binary with PyInstaller

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
        pip install -r requirements/requirements_dev.txt
        pip install pyinstaller

    - name: Build binary
      run: |
        invoke build-binary

    - name: Test the binary
      run:
        invoke test-binary

    - name: Prepare binary for upload
      run:
        invoke prepare-binary

